### ISSUE TITLE
Mapa Mental Web 3.0 

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/mapa-mental-web-3-IsraelNicolas61#1]
[MapaMentalWEB3.0_IsraelNicolás.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-IsraelNicolas61/files/8386424/MapaMentalWEB3.0_IsraelNicolas.pdf)

**Comment by Abraham890** [comment]
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
